project_id = "qtsboanwhzskkdvkfcdt"

[functions.parse-pdf]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.places-details]
verify_jwt = false

[functions.xero-apply-payment]
verify_jwt = false

[functions.xero-auth]
verify_jwt = false

[functions.xero-bank-transactions]
verify_jwt = false

[functions.xero-callback]
verify_jwt = false

[functions.xero-contacts]
verify_jwt = false

[functions.xero-create-contact]
verify_jwt = false

[functions.xero-create-invoice]
verify_jwt = false

[functions.xero-delete-invoice]
verify_jwt = false

[functions.xero-invoices]
verify_jwt = false

[functions.xero-check-payment]
verify_jwt = false

[functions.xero-next-invoice-number]
verify_jwt = false

[functions.rewrite-text]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.send-sms-reminder]
verify_jwt = false

[functions.send-voice-reminder]
verify_jwt = false

[functions.send-chase-email]
verify_jwt = false

[functions.send-thank-you-email]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.xero-update-invoice-status]
verify_jwt = false

[functions.send-statement-email]
verify_jwt = false

[functions.xero-suppliers]
verify_jwt = false

[functions.xero-create-supplier]
verify_jwt = false

[functions.xero-create-purchase-order]
verify_jwt = false

[functions.xero-update-purchase-order-status]
verify_jwt = false

[functions.xero-delete-purchase-order]
verify_jwt = false

[functions.companies-house]
verify_jwt = false

[functions.analyze-customer-intelligence]
verify_jwt = false

[functions.sync-invoice-status]
verify_jwt = false

[functions.microsoft-auth]
verify_jwt = false

[functions.microsoft-callback]
verify_jwt = false

[functions.upload-to-sharepoint]
verify_jwt = false
