import puppeteer from "puppeteer-core";
import fs from "fs";
const browser = await puppeteer.launch({ executablePath: "/bin/chromium", headless: "new", args: ["--no-sandbox","--disable-gpu"] });
const page = await browser.newPage();
page.on("console", m => console.log("[c]", m.type(), m.text().slice(0,200)));
page.on("pageerror", e => console.log("[err]", e.message));
await page.goto("http://localhost:8765/", { waitUntil: "networkidle0" });
await page.waitForFunction(() => document.title === "READY", { timeout: 15000 });
const png1 = await page.evaluate(() => (window as any)._png1);
const png2 = await page.evaluate(() => (window as any)._png2);
fs.writeFileSync("/tmp/sig_mike.png", Buffer.from(png1.split(",")[1], "base64"));
fs.writeFileSync("/tmp/sig_bholden.png", Buffer.from(png2.split(",")[1], "base64"));
console.log("done", png1.length, png2.length);
await browser.close();
