/**
 * Tendering bolt-on service layer.
 * CRUD wrappers + type defs for tenders, company documents, and
 * tender pack items. The `(supabase as any)` casts are deliberate —
 * the Supabase types file gets regenerated by Lovable's pipeline and
 * lags behind new migrations, so typing each table explicitly here
 * keeps the rest of the codebase clean.
 */

import { supabase } from "@/integrations/supabase/client";

export type TenderStatus =
  | "discovered"
  | "watching"
  | "bidding"
  | "submitted"
  | "won"
  | "lost"
  | "dismissed";

export type CompanyDocumentCategory =
  | "company_profile"
  | "accreditation"
  | "insurance"
  | "sample"
  | "policy"
  | "case_study"
  | "other";

export interface Tender {
  id: string;
  source: string;
  source_id: string | null;
  title: string;
  buyer_name: string | null;
  buyer_org: string | null;
  description: string | null;
  url: string | null;
  value_min: number | null;
  value_max: number | null;
  currency: string | null;
  region: string | null;
  published_at: string | null;
  deadline_at: string | null;
  status: TenderStatus;
  notes: string | null;
  tags: string[];
  discovered_at: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface CompanyDocument {
  id: string;
  title: string;
  category: CompanyDocumentCategory;
  description: string | null;
  file_url: string | null;
  file_storage_path: string | null;
  version: string | null;
  expires_at: string | null;
  is_archived: boolean;
  created_at: string;
  updated_at: string;
}

export interface TenderPackItem {
  id: string;
  tender_id: string;
  company_document_id: string | null;
  custom_title: string | null;
  custom_url: string | null;
  sort_order: number;
  notes: string | null;
  created_at: string;
  // Joined when listed
  company_document?: CompanyDocument | null;
}

// ─── Tenders ───────────────────────────────────────────────────────

export async function listTenders(filter?: {
  statuses?: TenderStatus[];
  search?: string;
}): Promise<Tender[]> {
  let q = (supabase as any).from("tenders").select("*").order("deadline_at", { ascending: true, nullsFirst: false });
  if (filter?.statuses && filter.statuses.length > 0) q = q.in("status", filter.statuses);
  if (filter?.search) {
    const s = filter.search.trim();
    if (s) q = q.or(`title.ilike.%${s}%,buyer_org.ilike.%${s}%,description.ilike.%${s}%`);
  }
  const { data, error } = await q;
  if (error) throw error;
  return (data ?? []) as Tender[];
}

export async function getTender(id: string): Promise<Tender | null> {
  const { data, error } = await (supabase as any)
    .from("tenders").select("*").eq("id", id).maybeSingle();
  if (error) throw error;
  return data as Tender | null;
}

export async function createTender(input: Partial<Tender> & { title: string }): Promise<Tender> {
  const { data: u } = await supabase.auth.getUser();
  const payload = { ...input, created_by: u.user?.id ?? null };
  const { data, error } = await (supabase as any)
    .from("tenders").insert(payload).select("*").single();
  if (error) throw error;
  return data as Tender;
}

export async function updateTender(id: string, patch: Partial<Tender>): Promise<void> {
  const { error } = await (supabase as any)
    .from("tenders").update({ ...patch, updated_at: new Date().toISOString() }).eq("id", id);
  if (error) throw error;
}

export async function deleteTender(id: string): Promise<void> {
  const { error } = await (supabase as any).from("tenders").delete().eq("id", id);
  if (error) throw error;
}

export async function tenderStatusCounts(): Promise<Record<TenderStatus, number>> {
  const { data, error } = await (supabase as any)
    .from("tenders").select("status");
  if (error) throw error;
  const counts: Record<TenderStatus, number> = {
    discovered: 0, watching: 0, bidding: 0, submitted: 0, won: 0, lost: 0, dismissed: 0,
  };
  for (const row of (data as Array<{ status: TenderStatus }>) ?? []) counts[row.status]++;
  return counts;
}

// ─── Company documents ────────────────────────────────────────────

export async function listCompanyDocuments(opts?: {
  category?: CompanyDocumentCategory;
  includeArchived?: boolean;
}): Promise<CompanyDocument[]> {
  let q = (supabase as any)
    .from("company_documents").select("*").order("category").order("title");
  if (opts?.category) q = q.eq("category", opts.category);
  if (!opts?.includeArchived) q = q.eq("is_archived", false);
  const { data, error } = await q;
  if (error) throw error;
  return (data ?? []) as CompanyDocument[];
}

export async function createCompanyDocument(
  input: Partial<CompanyDocument> & { title: string; category: CompanyDocumentCategory },
): Promise<CompanyDocument> {
  const { data, error } = await (supabase as any)
    .from("company_documents").insert(input).select("*").single();
  if (error) throw error;
  return data as CompanyDocument;
}

export async function updateCompanyDocument(id: string, patch: Partial<CompanyDocument>): Promise<void> {
  const { error } = await (supabase as any)
    .from("company_documents").update({ ...patch, updated_at: new Date().toISOString() }).eq("id", id);
  if (error) throw error;
}

export async function deleteCompanyDocument(id: string): Promise<void> {
  const { error } = await (supabase as any).from("company_documents").delete().eq("id", id);
  if (error) throw error;
}

// ─── Pack items ───────────────────────────────────────────────────

export async function listPackItems(tenderId: string): Promise<TenderPackItem[]> {
  const { data, error } = await (supabase as any)
    .from("tender_pack_items")
    .select("*, company_document:company_documents(*)")
    .eq("tender_id", tenderId)
    .order("sort_order");
  if (error) throw error;
  return (data ?? []) as TenderPackItem[];
}

export async function addPackItem(input: {
  tender_id: string;
  company_document_id?: string | null;
  custom_title?: string | null;
  custom_url?: string | null;
  sort_order?: number;
  notes?: string | null;
}): Promise<TenderPackItem> {
  const { data, error } = await (supabase as any)
    .from("tender_pack_items").insert(input).select("*").single();
  if (error) throw error;
  return data as TenderPackItem;
}

export async function removePackItem(id: string): Promise<void> {
  const { error } = await (supabase as any).from("tender_pack_items").delete().eq("id", id);
  if (error) throw error;
}

export async function reorderPackItems(items: { id: string; sort_order: number }[]): Promise<void> {
  // Batched upserts via Promise.all — N small updates rather than a
  // single complex query. Lists are typically <20 items so this is fine.
  await Promise.all(
    items.map((it) =>
      (supabase as any).from("tender_pack_items").update({ sort_order: it.sort_order }).eq("id", it.id),
    ),
  );
}

// ─── Status labels (UI-side helpers) ─────────────────────────────

export const TENDER_STATUS_LABELS: Record<TenderStatus, string> = {
  discovered: "Discovered",
  watching: "Watching",
  bidding: "Bidding",
  submitted: "Submitted",
  won: "Won",
  lost: "Lost",
  dismissed: "Dismissed",
};

export const COMPANY_DOC_CATEGORY_LABELS: Record<CompanyDocumentCategory, string> = {
  company_profile: "Company profile",
  accreditation: "Accreditation",
  insurance: "Insurance",
  sample: "Sample report",
  policy: "Policy",
  case_study: "Case study",
  other: "Other",
};
