-- One-off backfill: stub a service_reports row for every completed
-- callout / emergency / remedial visit that doesn't already have one.
--
-- Why
--   Pre-PR #170, generate-callout-docx generated a DOCX/PDF, uploaded
--   it to the callout-outputs storage bucket, and walked away — no DB
--   row was ever written. So the dashboard's "No report" badge fired
--   forever on those visits even though the PDF existed.
--
--   #170 fixed this going forward by writing a service_reports row
--   tagged status='callout' at generation time. This migration clears
--   the historical mess so the user doesn't have to click "Mark as
--   Reported & Close" on every old visit.
--
-- Scope
--   visit_type IN ('callout', 'emergency', 'remedial')
--   status     = 'completed'
--   engineer_id IS NOT NULL          -- required for created_by NOT NULL
--   no existing service_reports row for the visit (any status)
--
-- Discriminator
--   Inserted rows use status='callout' (matches #170), so a future
--   cleanup query can tell stub backfills apart from real
--   service_reports generated by the BS5839 capture wizard.
--
-- Idempotency
--   The NOT EXISTS guard means re-running this migration inserts
--   nothing. Safe to apply more than once.

DO $$
DECLARE
  inserted_count integer;
BEGIN
  WITH inserted_rows AS (
    INSERT INTO public.service_reports (
      visit_id,
      site_id,
      created_by,
      report_date,
      status,
      checklist
    )
    SELECT
      v.id,
      v.site_id,
      v.engineer_id,
      v.visit_date,
      'callout',
      '{}'::jsonb
    FROM public.service_visits v
    WHERE v.visit_type IN ('callout', 'emergency', 'remedial')
      AND v.status = 'completed'
      AND v.engineer_id IS NOT NULL
      AND NOT EXISTS (
        SELECT 1
        FROM public.service_reports r
        WHERE r.visit_id = v.id
      )
    RETURNING 1
  )
  SELECT COUNT(*) INTO inserted_count FROM inserted_rows;

  RAISE NOTICE 'callout/remedial service_reports backfill: % rows inserted', inserted_count;
END $$;
