
ALTER TABLE public.sites
  ADD COLUMN IF NOT EXISTS num_manual_call_points integer,
  ADD COLUMN IF NOT EXISTS num_sounders integer,
  ADD COLUMN IF NOT EXISTS num_detectors integer,
  ADD COLUMN IF NOT EXISTS arc_provider text,
  ADD COLUMN IF NOT EXISTS arc_account_ref text,
  ADD COLUMN IF NOT EXISTS access_hours text,
  ADD COLUMN IF NOT EXISTS duty_holder_name text,
  ADD COLUMN IF NOT EXISTS duty_holder_role text,
  ADD COLUMN IF NOT EXISTS duty_holder_email text,
  ADD COLUMN IF NOT EXISTS duty_holder_phone text,
  ADD COLUMN IF NOT EXISTS has_pava boolean,
  ADD COLUMN IF NOT EXISTS pava_make text,
  ADD COLUMN IF NOT EXISTS pava_model text,
  ADD COLUMN IF NOT EXISTS pava_software_version text,
  ADD COLUMN IF NOT EXISTS pava_bs_en_54_16_compliant boolean,
  ADD COLUMN IF NOT EXISTS pava_bs_en_54_24_compliant boolean,
  ADD COLUMN IF NOT EXISTS pava_num_zones integer,
  ADD COLUMN IF NOT EXISTS pava_num_loudspeakers integer,
  ADD COLUMN IF NOT EXISTS pava_num_circuits integer,
  ADD COLUMN IF NOT EXISTS pava_fa_interface_method text,
  ADD COLUMN IF NOT EXISTS pava_network_topology text,
  ADD COLUMN IF NOT EXISTS pava_has_backup_amplifier boolean;
